### PR TITLE
Restore optional cache target

### PR DESCRIPTION
**Pull request by sbquinlan**
Currently leaving the CacheTarget as it's default empty string throws:

```
(base) [ec2-user@ip-172-31-19-37 pangeo-forge-recipes]$ pangeo-forge-runner bake --repo=$(pwd) --feedstock-subdir=./recipes/mursst/
Target Storage is FSSpecTarget(LocalFileSystem(, root_path="/home/ec2-user/pangeo-forge-recipes/data/{job_name}")

Input Cache Storage is CacheFSSpecTarget(AbstractFileSystem(, root_path="")

Metadata Cache Storage is MetadataTarget(LocalFileSystem(, root_path="/home/ec2-user/pangeo-forge-recipes/data/{job_name}/cache/metadata")

Traceback (most recent call last):
  File "/home/ec2-user/micromamba/bin/pangeo-forge-runner", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/micromamba/lib/python3.9/site-packages/pangeo_forge_runner/cli.py", line 28, in main
    app.start()
  File "/home/ec2-user/micromamba/lib/python3.9/site-packages/pangeo_forge_runner/cli.py", line 23, in start
    super().start()
  File "/home/ec2-user/micromamba/lib/python3.9/site-packages/traitlets/config/application.py", line 474, in start
    return self.subapp.start()
  File "/home/ec2-user/micromamba/lib/python3.9/site-packages/pangeo_forge_runner/commands/bake.py", line 184, in start
    cache_target = input_cache_storage.get_forge_target(job_name=self.job_name)
  File "/home/ec2-user/micromamba/lib/python3.9/site-packages/pangeo_forge_runner/storage.py", line 59, in get_forge_target
    return cls(
  File "<string>", line 5, in __init__
  File "/home/ec2-user/micromamba/lib/python3.9/site-packages/pangeo_forge_recipes/storage.py", line 148, in __post_init__
    if not self.fs.isdir(self.root_path):
  File "/home/ec2-user/micromamba/lib/python3.9/site-packages/fsspec/spec.py", line 721, in isdir
    return self.info(path)["type"] == "directory"
  File "/home/ec2-user/micromamba/lib/python3.9/site-packages/fsspec/spec.py", line 681, in info
    out = self.ls(self._parent(path), detail=True, **kwargs)
  File "/home/ec2-user/micromamba/lib/python3.9/site-packages/fsspec/spec.py", line 350, in ls
    raise NotImplementedError
NotImplementedError
```

This change fixes that by restoring the former behavior of ignoring the default config (of empty string).

### CODE REVIEW

**Comment by cisaacstern** [comment]
LGTM @sbquinlan!

A basic test would be great.

I don't think we have a test_storage.py yet, so testing might require adding that module.

**Comment by cisaacstern** [comment]
Just a note to say IMO we can merge this as soon as a test is added.

**Comment by sbquinlan** [comment]
@cisaacstern yeah I'm just caught up in other things. I'll try come back to this pr this week.

**Comment by cisaacstern** [comment]
No rush from my end! Thanks!

**Comment by cisaacstern** [comment]
Dataflow tests are failing because the head branch is from a fork, so credentials are not available in Github Workflows.

But that's okay, because the unit tests are convincing in themselves!

Thanks @sbquinlan!

**Pull request merged**
