### PR TITLE
Inject target_root for kerchunk writer

### PR DESCRIPTION
**Pull request by cisaacstern**
This should be superseded eventually by a more general entry point system, but for now we need something like this to support kerchunk recipes.

### CODE REVIEW

**Comment by yuvipanda** [comment]
Generic injection system is in https://github.com/pangeo-forge/pangeo-forge-runner/pull/86. https://github.com/pangeo-forge/pangeo-forge-recipes/pull/566 is how recipes will tell runner what to inject. I'm guessing this particular transform isn't in 0.10, so simply merging https://github.com/pangeo-forge/pangeo-forge-recipes/pull/566 should be enough.

**Comment by cisaacstern** [comment]
Thanks so much for all this work, @yuvipanda! I'm gradually getting up to speed...

> I'm guessing this particular transform isn't in 0.10

Actually, this _is_ in `0.10.0` and the fact that it was released without realizing this incompatibility is partly a reflection of the lack on bi-directional integration testing (which you and I have previously discussed, and I'm working on, more on that soon...).

> so simply merging https://github.com/pangeo-forge/pangeo-forge-recipes/pull/566 should be enough

So this won't be sufficient for getting this transform to be backwards-compatibility supported in `0.10.0`, but I'm comfortable with that. We can just release `0.10.1` with the note that folks should use that if they want this feature.

**Comment by cisaacstern** [comment]
If it's alright with you, I'm going to wait to close this until #86 and associated work is merged, as a reminder to myself to make sure this specific issue is resolved by that (which I assume it will be, but the mental note is helpful to me nonetheless).

**Comment by yuvipanda** [comment]
@cisaacstern ah good to know this was in 0.10! I've added this to the backwards compat shim in https://github.com/pangeo-forge/pangeo-forge-runner/pull/86/commits/2e0fd04e5946a13f49a574b233ee80fdebffc30b. No new release needed.

No problem keeping this open until those are merged.

**Comment by cisaacstern** [comment]
Ty ty!

**Comment by cisaacstern** [comment]
superseded by #86

**Pull request closed without merging**
