### PR TITLE
Hardcoded pangeo/forge image tag is broken, make container image configurable

### PR DESCRIPTION
**Pull request by cisaacstern**
See https://github.com/pangeo-forge/pangeo-forge-orchestrator/issues/156#issuecomment-1264175655 for context.

### CODE REVIEW

**Comment by cisaacstern** [comment]
The issue discussed in https://github.com/pangeo-forge/pangeo-forge-orchestrator/issues/156#issuecomment-1264175655 suggests we should probably be running some type of periodic tests on Dataflow itself. I'm happy to think about that at a later date, but don't have time to work on the details at this moment. It's an important issue, so IMO anyone else is welcome to work on it before I get to it, which might be a while.

**Comment by cisaacstern** [comment]
Per https://github.com/pangeo-forge/pangeo-forge-orchestrator/issues/156#issuecomment-1264176835, probably the easiest thing is to set the latest pin of https://github.com/pangeo-data/pangeo-docker-images/tree/master/forge as the default value of the `container_image`, and see if that works. Assuming it does, then periodic tests on Dataflow would help catch issues such as https://github.com/pangeo-forge/pangeo-forge-orchestrator/issues/156 early.

**Comment by yuvipanda** [comment]
@cisaacstern you still need https://github.com/pangeo-data/pangeo-docker-images/pull/379 to get a newer beam, but this should help unblock you when that does come.

**Comment by cisaacstern** [comment]
Thanks @yuvipanda!

**Pull request merged**
