### PR TITLE
Fix `"multi_processing"` typo to match `direct_running_mode` expected by Beam

### PR DESCRIPTION
**Pull request by derekocallaghan**
Fixes pangeo-forge/pangeo-forge-runner#41

### CODE REVIEW

**Comment by yuvipanda** [comment]
Wheeee, thank you very much, @derekocallaghan!!!!

**Comment by derekocallaghan** [comment]
> The dodecov failure is definitely a bug on their part, so gonna merge this one.

Thanks @yuvipanda, I see the "Closed with unmerged commits" message above, I guess the commit isn't merged yet so I'll hold off on deleting my branch for now.

**Comment by yuvipanda** [comment]
oh shit i hit the wrongb button

**Comment by yuvipanda** [comment]
Correct button hit, yay! Thank you so much for the PR :) Hope to see more! I'll prioritize reviewing them...

Would you like to make a release? I can give you merge rights to the repo as well as PyPI rights, if you want :)

**Comment by derekocallaghan** [comment]
> Correct button hit, yay! Thank you so much for the PR :) Hope to see more! I'll prioritize reviewing them...
> 
> Would you like to make a release? I can give you merge rights to the repo as well as PyPI rights, if you want :)

It's only a small change and I think the Beam usage will work without it, it'll just choose a different runtime environment, so maybe there's no need for a release for now until there are some other commits to include?

BTW, I had some suggestions today for one of the [user-stories issues that would involve some `pangeo-forge-runner` changes](https://github.com/pangeo-forge/user-stories/issues/13#issuecomment-1303586954), I can create a new issue in this repo for this but was planning to leave discussion for now in the user-stories repo depending on feedback.

**Pull request merged**
