### PR TITLE
Allow setting maximum number of workers a dataflow job can have

### PR DESCRIPTION
**Pull request by yuvipanda**
Helps to make sure we don't hammer our source servers.

### CODE REVIEW

**Comment by cisaacstern** [comment]
@yuvipanda, is your understanding that this will function as a type of concurrency limiter, because individual workers will not attempt more than one concurrent caching operation?

**Comment by yuvipanda** [comment]
@cisaacstern yes, and in practice it has worked as such. The caching step seems to be the one most parallelizable, and is what seems to be most affected by this.

**Comment by cisaacstern** [comment]
@yuvipanda that's incredible! When I tried to run the full temporal range of https://github.com/pangeo-forge/staged-recipes/pull/151 on Dataflow, the autoscaler spawned 1000 workers (maximum allowed by Columbia's GCP project), which all simultaneously ground to a halt because they (of course) overwhelmed the source server with an accidental pseudo-DDoS attack. So happy to see such an elegant solution to this problem 😄

**Comment by yuvipanda** [comment]
@cisaacstern haha yes i went through the same process :)

**Pull request merged**
