### PR TITLE
Set default to multi_processing

### PR DESCRIPTION
**Pull request by moradology**
@yuvipanda Made as a PR so that you can take this change or leave it, but it may help us to get the backlog clear

### CODE REVIEW

**Comment by ranchodeluxe** [comment]
This should be fine if unit tests pass b/c of this: https://github.com/pangeo-forge/pangeo-forge-runner/blob/main/pangeo_forge_runner/bakery/local.py#L43

**Comment by ranchodeluxe** [comment]
looking into the test fix now 👀

**Comment by moradology** [comment]
Test failure here is just due to a bad import as we're installing from a branch that has moved forward... I'd suggest a rebase after this PR goes into yuvi's PR

**Comment by moradology** [comment]
I'm going to be a bad boy and go for this merge. @yuvipanda I'm sorry!

**Pull request merged**
