### PR TITLE
Arbitrary injections

### PR DESCRIPTION
**Pull request by cisaacstern**
WIP with @jbusecke to support arbitrary callable args injections.

Motivated by the desire to create "template recipes" for CMIP6 which can be called with arbitrary input parameters at recipe parse time.

### CODE REVIEW

**Comment by cisaacstern** [comment]
In @jbusecke and my limited testing, this featured worked for injecting a value into a "template recipe", here:

> https://github.com/jbusecke/cmip6-leap-feedstock/blob/b0b72071935346a9630bff5f37e3b887e10c7481/feedstock/recipe.py#L12-L25

More thought can be given to how to best generalize this feature. The reserved function name we use currently is not as flexible as I imagine we'd want this to be before merging.

**Comment by cisaacstern** [comment]
> The reserved function name we use currently is not as flexible as I imagine we'd want this to be before merging.

@jbusecke, as of the last commit you can now call the `inject_func` in your recipe module whatever name you'd like. And as noted in the updated docstring, you will now pass the injection as a nested JSON-formatted dict, e.g.

```
--inject='{"get_some_value": {"value": 123}}'
```

where `get_some_value` is the function name, with argument `value`, defined in the recipe module. This also means you should be able to use arbitrary numbers of such functions, i.e.

```
--inject='{"get_some_value": {"value": 123}, "get_another_value": {"value": 456}}'
```
assuming `get_some_value` and `get_another_value` are both functions defined in your recipe module (with no limit on the number of such functions you can use).

**Comment by yuvipanda** [comment]
https://github.com/pangeo-forge/pangeo-forge-runner/pull/86 is the plugin system for injections. However, I think that's a bit different from what is happening here. This is more of a 'traitlets pass through' - you want to have one recipe, and feed it different options from the commandline. Is that right?

Is there code that's using this already? One primary question for me is how this would affect the model of a recipe being reproducible. Right now, the params you pass on the commandline don't actually affect the *work* being done - only where it's sent to or cached or whatever. How would that change?

**Comment by jbusecke** [comment]
I think those are valid concerns, and in fact @cisaacstern and I have gone a [different route](https://github.com/leap-stc/cmip6-leap-feedstock/pull/9) with the CMIP6 feedstock. I am not sure that this method is better in terms of reproducibility, but it works for now.

**Comment by cisaacstern** [comment]
Yes, as noted by @jbusecke, we are not using this actively, and while I can't say for sure _how_ much better the current approach is, I think it is more intelligible than this, and am happy to see this be closed, as I was concerned that it was far too permissive (despite being the one who authored it 😆 ). Which is a long way of saying, thanks for taking a look, and I'll close now!

**Pull request closed without merging**
