### PR TITLE
Enable vertical autoscaling when dataflow prime is enabled

### PR DESCRIPTION
**Pull request by yuvipanda**
Fixes https://github.com/pangeo-forge/pangeo-forge-runner/issues/95

### CODE REVIEW

**Comment by jbusecke** [comment]
I am not sure if this is actually working. I submitted [this](https://console.cloud.google.com/dataflow/jobs/us-central1/2023-08-29_09_05_15-12190207985051774339;mainTab=JOB_METRICS;logsSeverity=ERROR;graphView=0?project=leap-pangeo&pageState=(%22dfTime%22:(%22l%22:%22dfJobMaxTime%22))) job (I think you should have access to view this). 
image

The job info fields are (I think) supposed to show this if enabled. See the screenshot in [here](https://blog.searce.com/dataflow-prime-whats-new-58f95cb768cd) for example.

**Comment by yuvipanda** [comment]
@jbusecke I do see them in the 'experiments' field though. In the screenshots, I see that they also are for a streaming job, rather than a batch job. 

Perhaps @alxmrs may know more about dataflow prime + vertical autoscaling?

**Comment by jbusecke** [comment]
Yeah these do not seem to scale vertically...
image

**Comment by jbusecke** [comment]
> @jbusecke I do see them in the 'experiments' field though. In the screenshots, I see that they also are for a streaming job, rather than a batch job.

Oh good catch! I am also just poking around here... not saying that I understand this properly lol.

**Comment by cisaacstern** [comment]
All tests passing, going to merge! 🚀

**Pull request merged**
