### PR TITLE
Remove support for pfr<=0.9.x

### PR DESCRIPTION
**Pull request by moradology**
This draft aims to move us towards cutting support for the older `to_beam` recipe version. This ought to simplify developer work and cut down on CI complexity. #144

### CODE REVIEW

**Review by ranchodeluxe — APPROVED** [review]
This looks good to me and once in unblocks some good work in:
https://github.com/pangeo-forge/pangeo-forge-runner/pull/171
https://github.com/pangeo-forge/pangeo-forge-runner/pull/166

**Comment by moradology** [comment]
@cisaacstern It occurs to me you might have an opinion here. I'm for pulling the trigger and moving things forward as i think there are further issues with the ways recipes are handled that will require potential further deprecation or at least heavy guidance on the semantics of the two approaches - PTransform construction vs lazily building our full pipeline inside a function that will serve as the recipe (this is enabled by the PR about lazy pipeline construction #168)

**Comment by cisaacstern** [comment]
Thanks for the ping I will take a look this afternoon.

**Review by cisaacstern — COMMENTED** [review]
Overall LGTM, @moradology, thanks so much for doing this overdue maintenance! One other thing we should remove as part of this PR is:

https://github.com/pangeo-forge/pangeo-forge-runner/blob/0eda0ca7e55c849fea6092b246899807e31f6b4e/pangeo_forge_runner/storage.py#L110-L115

Since that is only relevant in pre-0.10.0 releases.

Apart from that, I haven't taken a close look yet as to why codecov is upset, but if possible would be great to get that passing.

**Comment by ranchodeluxe** [comment]
well, codecov was complaining b/c the number of removals seemed to reduce the overall ratio of coverage, not b/c things changed too much. I added some `codecov.yml` rules that exclude `/tests/` and obvious things that the recipes repo excluded and we're gravy 🥳 

gonna merge this sucker

**Comment by cisaacstern** [comment]
Awesome! Thanks all!

**Pull request merged**
